# Service ID
update_token:
  fields:
    access_token:
      required: true
      example: "ey... long token"
      default: ""
    access_token:
      required: true
      example: "2024-01-01T12:34:00"
      default: ""
